# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _pyabcore
else:
    import _pyabcore

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _pyabcore.delete_SwigPyIterator

    def value(self):
        return _pyabcore.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _pyabcore.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _pyabcore.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _pyabcore.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _pyabcore.SwigPyIterator_equal(self, x)

    def copy(self):
        return _pyabcore.SwigPyIterator_copy(self)

    def next(self):
        return _pyabcore.SwigPyIterator_next(self)

    def __next__(self):
        return _pyabcore.SwigPyIterator___next__(self)

    def previous(self):
        return _pyabcore.SwigPyIterator_previous(self)

    def advance(self, n):
        return _pyabcore.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _pyabcore.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _pyabcore.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _pyabcore.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _pyabcore.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _pyabcore.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _pyabcore.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _pyabcore:
_pyabcore.SwigPyIterator_swigregister(SwigPyIterator)

class BoolVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _pyabcore.BoolVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyabcore.BoolVector___nonzero__(self)

    def __bool__(self):
        return _pyabcore.BoolVector___bool__(self)

    def __len__(self):
        return _pyabcore.BoolVector___len__(self)

    def __getslice__(self, i, j):
        return _pyabcore.BoolVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyabcore.BoolVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyabcore.BoolVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyabcore.BoolVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyabcore.BoolVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyabcore.BoolVector___setitem__(self, *args)

    def pop(self):
        return _pyabcore.BoolVector_pop(self)

    def append(self, x):
        return _pyabcore.BoolVector_append(self, x)

    def empty(self):
        return _pyabcore.BoolVector_empty(self)

    def size(self):
        return _pyabcore.BoolVector_size(self)

    def swap(self, v):
        return _pyabcore.BoolVector_swap(self, v)

    def begin(self):
        return _pyabcore.BoolVector_begin(self)

    def end(self):
        return _pyabcore.BoolVector_end(self)

    def rbegin(self):
        return _pyabcore.BoolVector_rbegin(self)

    def rend(self):
        return _pyabcore.BoolVector_rend(self)

    def clear(self):
        return _pyabcore.BoolVector_clear(self)

    def get_allocator(self):
        return _pyabcore.BoolVector_get_allocator(self)

    def pop_back(self):
        return _pyabcore.BoolVector_pop_back(self)

    def erase(self, *args):
        return _pyabcore.BoolVector_erase(self, *args)

    def __init__(self, *args):
        _pyabcore.BoolVector_swiginit(self, _pyabcore.new_BoolVector(*args))

    def push_back(self, x):
        return _pyabcore.BoolVector_push_back(self, x)

    def front(self):
        return _pyabcore.BoolVector_front(self)

    def back(self):
        return _pyabcore.BoolVector_back(self)

    def assign(self, n, x):
        return _pyabcore.BoolVector_assign(self, n, x)

    def resize(self, *args):
        return _pyabcore.BoolVector_resize(self, *args)

    def insert(self, *args):
        return _pyabcore.BoolVector_insert(self, *args)

    def reserve(self, n):
        return _pyabcore.BoolVector_reserve(self, n)

    def capacity(self):
        return _pyabcore.BoolVector_capacity(self)
    __swig_destroy__ = _pyabcore.delete_BoolVector

# Register BoolVector in _pyabcore:
_pyabcore.BoolVector_swigregister(BoolVector)

class Pyabcore(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    left = property(_pyabcore.Pyabcore_left_get, _pyabcore.Pyabcore_left_set)
    right = property(_pyabcore.Pyabcore_right_get, _pyabcore.Pyabcore_right_set)
    bicore_index_u = property(_pyabcore.Pyabcore_bicore_index_u_get, _pyabcore.Pyabcore_bicore_index_u_set)
    bicore_index_v = property(_pyabcore.Pyabcore_bicore_index_v_get, _pyabcore.Pyabcore_bicore_index_v_set)
    dir = property(_pyabcore.Pyabcore_dir_get, _pyabcore.Pyabcore_dir_set)
    g = property(_pyabcore.Pyabcore_g_get, _pyabcore.Pyabcore_g_set)
    n1 = property(_pyabcore.Pyabcore_n1_get, _pyabcore.Pyabcore_n1_set)
    n2 = property(_pyabcore.Pyabcore_n2_get, _pyabcore.Pyabcore_n2_set)

    def __init__(self, *args):
        _pyabcore.Pyabcore_swiginit(self, _pyabcore.new_Pyabcore(*args))

    def index(self, *args):
        return _pyabcore.Pyabcore_index(self, *args)

    def query(self, a, b):
        return _pyabcore.Pyabcore_query(self, a, b)

    def get_left(self):
        return _pyabcore.Pyabcore_get_left(self)

    def get_right(self):
        return _pyabcore.Pyabcore_get_right(self)
    __swig_destroy__ = _pyabcore.delete_Pyabcore

# Register Pyabcore in _pyabcore:
_pyabcore.Pyabcore_swigregister(Pyabcore)



